// Auto-generated by prebuild-links.mjs - DO NOT EDIT MANUALLY
import type { LinkMetadata } from '@/types'

export const staticLinkMetadata: Record<string, LinkMetadata> = {
  "https://github.com/": {
    "url": "https://github.com/",
    "title": "GitHub · Build and ship software on a single, collaborative platform",
    "description": "Join the world's most widely adopted, AI-powered developer platform where millions of developers, businesses, and the largest open source community build software that advances humanity.",
    "image": "https://github.githubassets.com/assets/home24-5939032587c9.jpg",
    "siteName": "GitHub",
    "favicon": "https://github.githubassets.com/favicons/favicon.svg",
    "fetchedAt": "2025-07-11T13:42:27.189Z"
  },
  "https://nextjs.org/": {
    "url": "https://nextjs.org/",
    "title": "Next.js by Vercel - The React Framework",
    "description": "Next.js by Vercel is the full-stack React framework for the web.",
    "image": "https://assets.vercel.com/image/upload/front/nextjs/twitter-card.png",
    "siteName": "@vercel",
    "favicon": "https://nextjs.org/favicon.ico",
    "fetchedAt": "2025-07-11T13:42:27.236Z"
  },
  "https://reactjs.org/": {
    "url": "https://reactjs.org/",
    "title": "React",
    "description": "React is the library for web and native user interfaces. Build user interfaces out of individual pieces called components written in JavaScript. React is designed to let you seamlessly combine compone",
    "image": "https://react.dev/images/og-home.png",
    "siteName": "@reactjs",
    "favicon": "https://reactjs.org/favicon-32x32.png",
    "fetchedAt": "2025-07-11T13:42:27.399Z"
  },
  "https://github.com/hashicorp/next-mdx-remote": {
    "url": "https://github.com/hashicorp/next-mdx-remote",
    "title": "GitHub - hashicorp/next-mdx-remote: Load MDX content from anywhere",
    "description": "Load MDX content from anywhere. Contribute to hashicorp/next-mdx-remote development by creating an account on GitHub.",
    "image": "https://opengraph.githubassets.com/ac76f838caf4f6d97a770f399a705c9c8352b1314c8d2639afa9ba3ddb9e72b5/hashicorp/next-mdx-remote",
    "siteName": "GitHub",
    "favicon": "https://github.githubassets.com/favicons/favicon.svg",
    "fetchedAt": "2025-07-11T13:42:27.728Z"
  },
  "https://github.com/awayatakuma/cdk-sqs-kinesis-performance-check": {
    "url": "https://github.com/awayatakuma/cdk-sqs-kinesis-performance-check",
    "title": "GitHub - awayatakuma/cdk-sqs-kinesis-performance-check",
    "description": "Contribute to awayatakuma/cdk-sqs-kinesis-performance-check development by creating an account on GitHub.",
    "image": "https://opengraph.githubassets.com/3335ed57f4f1e723fd931928e2f239397b5f3d291329d3ea1ba034fe3838204d/awayatakuma/cdk-sqs-kinesis-performance-check",
    "siteName": "GitHub",
    "favicon": "https://github.githubassets.com/favicons/favicon.svg",
    "fetchedAt": "2025-07-11T13:42:27.756Z"
  },
  "https://github.com/awayatakuma/asynctp.tokyo": {
    "url": "https://github.com/awayatakuma/asynctp.tokyo",
    "title": "GitHub - awayatakuma/asynctp.tokyo",
    "description": "Contribute to awayatakuma/asynctp.tokyo development by creating an account on GitHub.",
    "image": "https://opengraph.githubassets.com/7468b97c49ca9fa65c76feb831b642e060d47aeb86fe7d11973579c0e770e103/awayatakuma/asynctp.tokyo",
    "siteName": "GitHub",
    "favicon": "https://github.githubassets.com/favicons/favicon.svg",
    "fetchedAt": "2025-07-11T13:42:27.777Z"
  },
  "https://github.com/awayatakuma/message-queue-go-linkage": {
    "url": "https://github.com/awayatakuma/message-queue-go-linkage",
    "title": "GitHub - awayatakuma/message-queue-go-linkage",
    "description": "Contribute to awayatakuma/message-queue-go-linkage development by creating an account on GitHub.",
    "image": "https://opengraph.githubassets.com/8c3a96e02f03a2596278041cee3e049436376cbd0045e05b56f4e70936a8c8a5/awayatakuma/message-queue-go-linkage",
    "siteName": "GitHub",
    "favicon": "https://github.githubassets.com/favicons/favicon.svg",
    "fetchedAt": "2025-07-11T13:42:27.842Z"
  },
  "https://nextjs.org/docs/pages/building-your-application/configuring/mdx": {
    "url": "https://nextjs.org/docs/pages/building-your-application/configuring/mdx",
    "title": "Guides: MDX | Next.js",
    "description": "Learn how to configure MDX to write JSX in your markdown files.",
    "image": "https://nextjs.org/api/docs-og?title=Guides:%20MDX",
    "siteName": "nextjs.org",
    "favicon": "https://nextjs.org/favicon.ico",
    "fetchedAt": "2025-07-11T13:42:29.421Z"
  },
  "https://nextjs.org/docs/pages/building-your-application/configuring/mdx#remote-mdx": {
    "url": "https://nextjs.org/docs/pages/building-your-application/configuring/mdx#remote-mdx",
    "title": "Guides: MDX | Next.js",
    "description": "Learn how to configure MDX to write JSX in your markdown files.",
    "image": "https://nextjs.org/api/docs-og?title=Guides:%20MDX",
    "siteName": "nextjs.org",
    "favicon": "https://nextjs.org/favicon.ico",
    "fetchedAt": "2025-07-11T13:42:29.574Z"
  },
  "https://mdxjs.com/docs/troubleshooting-mdx": {
    "url": "https://mdxjs.com/docs/troubleshooting-mdx",
    "title": "Troubleshooting MDX | MDX",
    "description": "This article goes through several common problems and errors that might occur when using MDX.",
    "image": "https://mdxjs.com/docs/troubleshooting-mdx/index.png",
    "siteName": "MDX",
    "favicon": "https://mdxjs.com/favicon.ico",
    "fetchedAt": "2025-07-11T13:46:16.610Z"
  },
  "https://b.hatena.ne.jp/asynctp/bookmark": {
    "url": "https://b.hatena.ne.jp/asynctp/bookmark",
    "title": "asynctpのブックマーク - はてなブックマーク",
    "description": "No Description",
    "image": "",
    "siteName": "b.hatena.ne.jp",
    "favicon": "https://b.hatena.ne.jp/favicon.ico",
    "fetchedAt": "2025-07-11T14:09:02.138Z"
  },
  "https://note.com/asynctp/": {
    "url": "https://note.com/asynctp/",
    "title": "asynctp｜note",
    "description": "文系エンジニア。来世は宝石商か調香師になりたいです。\n発言は個人の見解に基づくものであり、所属組織を代表するものではありません。",
    "image": "https://assets.st-note.com/production/uploads/images/196331089/profile_c70b7343a5b64f6ae2e23a149f15f74a.png?fit=bounds&format=jpeg&quality=85&width=330",
    "siteName": "note（ノート）",
    "favicon": "https://assets.st-note.com/poc-image/manual/note-common-images/production/svg/production.ico",
    "fetchedAt": "2025-07-11T14:09:02.191Z"
  },
  "https://scrapbox.io/awayatakuma-biz-notes/": {
    "url": "https://scrapbox.io/awayatakuma-biz-notes/",
    "title": "asynctp-biz-notes",
    "description": "なぜ、あなたの仕事は終わらないのか スピードは最強の武器である / 読みたいことを、書けばいい。 人生が変わるシンプルな文章術 / 【新版】日本語の作文技術 / 科学哲学への招待 / 野家 啓一 / dotfiles / 改訂新版 内部構造から学ぶPostgreSQL 設計・運用計画の鉄則 / Explain EXPLAIN EXPLAINを使ったPostgreSQLのクエリ最適化の基本と実践 /",
    "image": "https://scrapbox.io/files/6829921270c35dee1936f672.png?type=thumbnail",
    "siteName": "asynctp-biz-notes",
    "favicon": "https://scrapbox.io/assets/img/favicon/favicon.ico",
    "fetchedAt": "2025-07-11T14:09:02.377Z"
  },
  "https://scrapbox.io/asynctp-favs/": {
    "url": "https://scrapbox.io/asynctp-favs/",
    "title": "asynctp-favs",
    "description": "asynctp / ハイパーインフレーション / 住吉九 / Mani Mani / 電音部 / 天 天和通りの快男児 / 福本伸行 / 衛府の七忍 / 山口貴由 / Biryani Tokyo / 蜜柑 / 芥川 竜之介 / ロビンズインドキッチン / 三燈舎 （SANTOSHAM） / ULTRAPANIC / Lanndo / Flight of The Ancients / The Sha",
    "image": "https://scrapbox.io/files/664992fd670e1e001c3909e2.png?type=thumbnail",
    "siteName": "asynctp-favs",
    "favicon": "https://scrapbox.io/assets/img/favicon/favicon.ico",
    "fetchedAt": "2025-07-11T14:09:02.388Z"
  }
}
